package com.pos.app.enums;

public enum ResponseEnum {
    SUCCESS,
    ERROR,
    ACCOUNT_ALREADY_EXIST, SIGN_IN_FAILED,
    ACCOUNT_NOT_FOUND,
    CLIENT_ALREADY_EXIST,
    CLIENT_NOT_FOUND,
    PIC_NOT_FOUND,
    PASSWORD_CHANGED_SUCCESSFULLY,
    INVALID_OLD_PASSWORD,
    ACCOUNT_DELETED_SUCCESSFULLY,
    UNAUTHORIZED,
    NUMBER_ALREADY_EXIST,
    CLIENT_REQUIRED, CLIENT_CATEGORY_ALREADY_EXIST, CATEGORY_NOT_FOUND, PRODUCTS_NOT_FOUND, ORDER_NOT_FOUND, ORDER_COMPLETED, WRONG_OLD_PASSWORD, REQUEST_INVALID, EMAIL_ALREADY_EXIST, ACCESS_DENIED
}
